#zf190430.1122

version: "3"

services:

    lighttpd:
      image: sebp/lighttpd
      volumes:
        - $PWD/www:/var/www/localhost/htdocs
        - $PWD/log:/var/log/lighttpd
#        - $PWD/etc/lighttpd:/etc/lighttpd
      ports:
        - "8081:80"
    


